title: The Eighth Oblivion Trilogy
description: When the machines woke, they did not rage. They simply continued. And that was far worse.
theme: jekyll-theme-minimal
markdown: kramdown
show_downloads: false
